# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc ""
  homepage ""
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/humanlogio/humanlog/releases/download/v0.7.0/humanlog_0.7.0_darwin_arm64.tar.gz"
      sha256 "7ed7f88e9eea57dbe302b5781caed4b8133ec5dd5ac0bc7ed049a5bd9e687b1b"

      def install
        bin.install "humanlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/humanlogio/humanlog/releases/download/v0.7.0/humanlog_0.7.0_darwin_amd64.tar.gz"
      sha256 "076459a43b9dd9a7c66e45c4e4ee59f947e63b11a65109fb870da1a68bdcbe84"

      def install
        bin.install "humanlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/humanlogio/humanlog/releases/download/v0.7.0/humanlog_0.7.0_linux_amd64.tar.gz"
      sha256 "e3ac0851f002a5b4020af4a059a14c77f8ea89185d05432d5dd273b43e925b3a"

      def install
        bin.install "humanlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanlogio/humanlog/releases/download/v0.7.0/humanlog_0.7.0_linux_arm64.tar.gz"
      sha256 "e7396d7844754bc45dff83fcc6d7f31726fc89fb378bd4b2a434db272c4a3b0f"

      def install
        bin.install "humanlog"
      end
    end
  end
end
